POST http://localhost:8080/api/v1/courses/fetch?year=2025&semester=SUMMER
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc2MjA5MTIyNSwiZXhwIjoxNzYyMTc3NjI1fQ.4n4UYghR1dhx9pAGyhNa2xDyxBJohHmSFrPGIeLe-nI